# GoReleaser configuration for binmate
# See https://goreleaser.com for documentation

version: 2

before:
  hooks:
    # Ensure dependencies are up to date
    - go mod download
    - go mod verify

builds:
  - id: binmate
    main: ./main.go
    binary: binmate
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
      # Windows build disabled due to CGO complexity with SQLite
      # - windows
    goarch:
      - amd64
      - arm64
    # Use flags for static linking where possible
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    # Platform-specific build settings for CGO
    overrides:
      - goos: linux
        goarch: amd64
        env:
          - CC=gcc
      - goos: linux
        goarch: arm64
        env:
          - CC=aarch64-linux-gnu-gcc
      - goos: darwin
        goarch: amd64
        env:
          - CC=o64-clang
      - goos: darwin
        goarch: arm64
        env:
          - CC=oa64-clang

archives:
  - id: binmate-archive
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - LICENSE*
      - README*
      - CHANGELOG*

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - 'typo'
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999

release:
  github:
    owner: cturner8
    name: copilot-cli-challenge
  draft: false
  prerelease: auto
  mode: append
  header: |
    ## Installation
    
    Use the install script:
    ```bash
    curl -fsSL https://raw.githubusercontent.com/cturner8/copilot-cli-challenge/main/install.sh | bash
    ```
    
    Or download the appropriate binary for your platform below.
  footer: |
    **Full Changelog**: https://github.com/cturner8/copilot-cli-challenge/compare/{{ .PreviousTag }}...{{ .Tag }}

# Snapshots (for testing releases locally)
snapshot:
  name_template: "{{ .Version }}-snapshot-{{.ShortCommit}}"
